### ISSUE TITLE
Error in system(paste0("ls -t1 shiny_bookmarks", " |  head -n 1"), intern = TRUE) :

### ISSUE THREAD

**Issue by yuhao1977** [UMMS-Biocore/debrowser#143]
tomorrow, I run the debrowser as usual in R, but it stopped, the followed error seemed related to the shiny, I want to know how to solve this problem. please help me.  debrowser is very important to me.

> startDEBrowser()
Error in system(paste0("ls -t1 shiny_bookmarks", " |  head -n 1"), intern = TRUE) : 
  'ls' not found

**Comment by nephantes** [comment]
Thanks pointing out this problem. We get this error on Windows machines. I fixed the problem in version 1.3.11.

**Comment by yuhao1977** [comment]
Dear nephantes:
    Thank you for solving this problem in time, when I  got your response, the DEBrowser came back soon, I can go on using this comprehensive package again.
    thank you very much.

**Comment by yuhao1977** [comment]
Dear nephantes:
Thank you for solving this problem in time, I found the newest version in the biocondunctor is 13.10, I don't know where to install the version 1.3.11, so I had to install the package from the github, the version is 0.99, the DEBrowser came back soon, I can go on using this comprehensive package again. but can you provide the web link to install or download the version 1.3.11?
thank you very much.

**Comment by nephantes** [comment]
I created a new release

**Comment by yuhao1977** [comment]
Dear nephantes:
The new release  still doesn't work on my computer for the same problem, I had to use the 0.99 ,maybe  this is my own bad luck.

**Comment by nephantes** [comment]
In this latest release I removed that line. It is not possible to get the same error. Could you send me how you are doing the installation? I can help you to remove and install DEBrowser version 1.3.11.

**Comment by yuhao1977** [comment]
Dear nephantes:
There is only one release that can work in my computer is 0.99 installed from github,
first, I removed the 1.3.10 in the Rstudio, and install the 0.99
this is my commands

library(githubinstall)
githubinstall('UMMS-Biocore/debrowser')

When you uploaded a new version to the bioconductor, then I removed the 0.99, and reinstalled the 1.3.11, this is my commands

source("https://bioconductor.org/biocLite.R")
biocLite("debrowser")
library(debrowser)
startDEBrowser()

and 
> startDEBrowser()
Error in system(paste0("ls -t1 shiny_bookmarks", " |  head -n 1"), intern = TRUE) : 
  'ls' not found

The same problem happened again, I have tried such instillation under R version from 3.3.1 to 3.3..3 in different PC, but it still doesn't work.

DEBrowser is the only reason for me to use R, the first version I used is 0.99，then 1.2.4 to 1.2.9, it helped me solving most data analyzing working conveniently， but now, it refused to work again, I feel very frustrated.
should removed all the packages and uninstall R, and reinstall DEBroser again?
Please help me, V-V

**Comment by nephantes** [comment]
You can install the latest version like this
source("https://bioconductor.org/biocLite.R")
biocLite("debrowser")

After that download zipped version to your desktop or anywhere using the link below.
https://github.com/UMMS-Biocore/debrowser/archive/develop.zip

Then install it using one of the commands below

a) in R;
install.packages(file.choose(), repos=NULL)
b) in R;
setwd("C:/Path_to_your_desktop");
install.packages("develop.zip", repos=NULL)

c)
make sure you have Rtools installed.
Make sure the R and Rtools paths are added in the environment variable.
Open a command prompt. Type R CMD INSTALL develop.zip

d) Another command prompt 
Rscript -e "install.packages('develop.zip', repos = NULL)"

Let me know how it goes.

**Comment by bioinfo17** [comment]
Hi,

I get this error:

package ‘debrowser’ is not available (for R version 3.2.2)
